### ISSUE TITLE
pip install libmc cannot install libmc

### ISSUE THREAD

**Issue by chen19901225** [douban/libmc#17]
error message:

 Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/Cython/: [Errno -2] Name or service not known -- Some packages may not be found!
    Couldn't find index page for 'Cython' (maybe misspelled?)
    No local packages or download links found for Cython>=0.20
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-hHVixe/libmc/setup.py", line 80, in <module>
        "pytest",
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 836, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1081, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1093, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 623, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('Cython>=0.20')

**Comment by mckelvin** [comment]
It looks  you have a problem accessing pypi.python.org. (Blame me if you can access https://pypi.python.org/simple/Cython/ in expectation.) If the problem continues, please try to use an alternative PyPI mirror (e.g.: http://pypi.douban.com/ ).

**Comment by chen19901225** [comment]
但是问题是.我用的就是豆瓣的源来的..
然后在docker build 的时候出问题了..

**Comment by mckelvin** [comment]
你的 `pip install libmc` 是在 Dockerfile 里定义的吗？你的宿主机配置了豆瓣PyPI源，但是Docker环境里没有配置才出现这个问题的吧？ 尝试下 吧 pip.conf COPY 一份到docker image里？

**Comment by chen19901225** [comment]
不是...
docker build里面的命令是这样子的:
RUN pip install -r /opt/pip-packages.txt -i http://pypi.douban.com/simple --trusted-host pypi.douban.com

requirement.txt是这样子的:

Beaker==1.6.5.post1
bottle==0.12.8
gevent==1.0.1
greenlet==0.4.5
Jinja2==2.7.3
lru-dict==1.1.1
MarkupSafe==0.23
meld3==1.0.2
MySQL-python==1.2.5
pycrypto==2.6.1
libmc
pymongo==2.8
pytz==2015.2
pyzmq==14.5.0
redis==2.10.3
requests==2.6.2
SQLAlchemy
supervisor==3.1.3
ujson==1.33
uWSGI

同事的虚拟机就没有问题..我的就是问题.好奇怪..

**Comment by mckelvin** [comment]
@chen19901225 需要先确认的一个问题是：你机器能正常访问 https://pypi.python.org/simple/Cython/ `curl -v https://pypi.python.org/simple/Cython/`(预期会301) 吗？你的同事的机器呢？

> RUN pip install -r /opt/pip-packages.txt -i http://pypi.douban.com/simple --trusted-host pypi.douban.com

印象当中这种命令安装的包的依赖包并不会使用 `-i http://pypi.douban.com/simple`，你的报错信息也证明这一点。先确保你能正常访问 https://pypi.python.org/simple/Cython/  吧。如果你和同事的虚拟机都在一个局域网里，应该不是GFW的问题，先检查下DNS配置。

**Comment by cangling20041616** [comment]
docker build 总是不成功，后来手动pip 装成功了，感觉大神指点我这个小菜鸟。。

**Comment by mckelvin** [comment]
:clap:
